---
title: "matrisome_median_analysis"
author: "Tim Nieuwenhuis"
date: "11/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(pheatmap)

load("median_gtex_v8.rda")

#Select v8 or v7
#median_tpm <- read.csv("median_tpm_v7.csv", stringsAsFactors = F)
median_tpm <- read.csv("median_tpm_v8.csv", stringsAsFactors = F)



matrisome_tab <- read.csv("matrisome_hs_masterlist_EDIT_r.csv", stringsAsFactors = F)
colnames(matrisome_tab)[1] <- "Division"

matrisome_tab <- matrisome_tab %>% filter(Division != "Retired")

core_tab <- filter(matrisome_tab, Division == "Core matrisome")

assoc_tab <- filter(matrisome_tab, Division == "Matrisome-associated")


matrisome_tab[1:3,1:3]
```


```{r cars}
rownames(median_dat) <- gtab$gene_name
median_dat[1:3,1:3]

#Filter to matrisome
ind <- rownames(median_dat) %in% matrisome_tab$Gene.Symbol

median_dat_matrisome <- median_dat[ind,]

#Filter to core

ind <- rownames(median_dat) %in% core_tab$Gene.Symbol 

median_dat_core <- median_dat[ind,]

#Filter to assoc

ind <- rownames(median_dat) %in% assoc_tab$Gene.Symbol 

median_dat_assoc <- median_dat[ind,]


```


Cluster tissues
```{r}
#All matrisome
matrisome_cor <- cor(median_dat_matrisome, method = "kendall")

pheatmap(matrisome_cor,
                
                main="", fontsize=5, fontsize_row=5, fontsize_col=5,
                filename="all_matrisome_correlation_v8.pdf",
                width=7, height=7)

#Core matrisome
core_cor <- cor(median_dat_core, method = "kendall")

pheatmap(core_cor,
                
                main="", fontsize=5, fontsize_row=5, fontsize_col=5,
                filename="core_matrisome_correlation_v8.pdf",
                width=7, height=7)

```




Percent transcriptome tpm core vs assoc
```{r}
colsum_tpm <- colSums(median_tpm[,-1])

core_med_tpm <- colSums(filter(median_tpm, Description %in% core_tab$Gene.Symbol)[,-1])/colsum_tpm

#assoc_med_tpm <- colSums(filter(median_tpm, Description %in% assoc_tab$Gene.Symbol)[,-1])/colsum_tpm

assoc_med_tpm <- colSums(filter(median_tpm, Description %in% filter(assoc_tab, Category == "ECM Regulators")[,3])[,-1])/colsum_tpm
names(assoc_med_tpm) <- colnames(median_dat)

core_med_tpm <- enframe(core_med_tpm) 
core_med_tpm$type <- "Core Matrisome"


assoc_med_tpm <- enframe(assoc_med_tpm)
assoc_med_tpm$type <- "Associated Matrisome"

percent_dat <- rbind(core_med_tpm, assoc_med_tpm)

#percent_dat$name <- factor(x =colnames(median_dat), levels = rev(unique(colnames(median_dat))) )

ggplot(percent_dat) +
  geom_bar(aes(y = value, x = name, fill = type), stat = "identity") +
  scale_y_continuous(labels = scales::percent) +
  labs(y = "Percent TPM of Transcriptome",
       x = "Tissues") +
  scale_fill_discrete(name = "Protein Type") +
  coord_flip(ylim=c(0,.125)) 


ggsave(filename = "percent_transcriptome_matrisome_v8.pdf", width = 10, height = 10)

```

Percent transcriptome core types

```{r}
core_types <- unique(core_tab$Category)

glyco_percent <- colSums(filter(median_tpm, Description %in% filter(core_tab, Category == core_types[1])[,3])[,-1])/colsum_tpm

glyco_percent <- enframe(glyco_percent) 
glyco_percent$type <- core_types[1]

  
collagen_percent <- colSums(filter(median_tpm, Description %in% filter(core_tab, Category == core_types[2])[,3])[,-1])/colsum_tpm

collagen_percent <- enframe(collagen_percent) 
collagen_percent$type <- core_types[2]
  
proteoglycan_percent <- colSums(filter(median_tpm, Description %in% filter(core_tab, Category == core_types[3])[,3])[,-1])/colsum_tpm

proteoglycan_percent <- enframe(proteoglycan_percent) 
proteoglycan_percent$type <- core_types[3]


core_percent <- rbind(glyco_percent, collagen_percent, proteoglycan_percent)


core_percent$type <- factor(x = core_percent$type, levels = c("Proteoglycans", "Collagens","ECM Glycoproteins") )

#core_percent$name <- factor(x = colnames(median_dat), levels = rev(unique(colnames(median_dat))) )

ggplot(core_percent) +
  geom_bar(aes(y = value, x = name, fill = type), stat = "identity") +
  scale_y_continuous(labels = scales::percent) +
  coord_flip() +
  labs(y = "Percent TPM of Transcriptome",
       x = "Tissues") +
  scale_fill_discrete(name = "Protein Type")

ggsave(filename = "percent_transcriptome_core_matrisome_v8.pdf", width = 10, height = 10)
```
How much of pancreas expression is PRSS1 and PRSS2?

```{r}
panc_dat <- median_tpm %>% select( Description,Pancreas)

enzymes <- panc_dat %>% filter(Description %in% c("PRSS1", "PRSS2", "REG1A", "CELA3A"))

sum(enzymes$Pancreas)/sum(panc_dat$Pancreas)

#V7 test

median_tpm_v7 <- read.csv("median_tpm_v7.csv", stringsAsFactors = F)

panc_dat <- median_tpm_v7 %>% select( Description,Pancreas)

enzymes <- panc_dat %>% filter(Description %in% c("PRSS1", "PRSS2", "REG1A", "CELA3A"))

sum(enzymes$Pancreas)/sum(panc_dat$Pancreas)

```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
